from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from datetime import datetime
from typing import List, Optional, Dict, Any
from backend.api.v1.deps import get_current_user
from backend.mcp_servers.booking_mcp import BookingMCP # Import the new MCP

router = APIRouter(prefix="/booking", tags=["Booking"])

# Initialize the Booking Tool
booking_agent = BookingMCP()
bookings_db = [] # In-memory store

# --- UPDATED REQUEST SCHEMA ---
class BookingRequest(BaseModel):
    place_id: str
    place_name: str 
    place_address: Optional[str] = "" # Needed for fallback logic
    time: str # ISO String
    booking_url: Optional[str] = None 

# --- UPDATED RESPONSE SCHEMA ---
class BookingResponse(BaseModel):
    booking_id: int
    status: str      # e.g., "handoff", "confirmed", "failed"
    action_url: str  # The smart link generated by the Agent
    message: str     # Agent's reasoning text
    provider: str    # Who is handling this? (OpenTable, Google, etc.)

@router.post("/", response_model=BookingResponse)
def create_booking(
    request: BookingRequest,
    user_id: str = Depends(get_current_user)
):
    # 1. Delegate Logic to the MCP Agent
    agent_decision = booking_agent.generate_booking_action(
        place_name=request.place_name,
        address=request.place_address,
        booking_time=request.time,
        raw_url=request.booking_url
    )
    
    # 2. Log the "Attempt" (Simulating a database transaction)
    booking_id = len(bookings_db) + 1
    booking_record = {
        "id": booking_id,
        "user_id": user_id,
        "place_id": request.place_id,
        "time": request.time,
        "status": "initiated",
        "provider": agent_decision["provider"]
    }
    bookings_db.append(booking_record)
    
    # 3. Return the Agent's Decision to the Frontend
    return {
        "booking_id": booking_id,
        "status": agent_decision["status"],
        "action_url": agent_decision["action_url"],
        "message": agent_decision["message"],
        "provider": agent_decision["provider"]
    }